### ISSUE TITLE
Xcode 9.0 issues

### ISSUE THREAD

**Issue by slash7** [NextLevel/NextLevel#100]
Xcode 9.0

I encounter type issues (about 75 of them):

```swift
AVMediaType' (aka 'NSString') is not implicitly convertible to 'String!'; did you mean to use 'as' to explicitly convert?
```
In :

```swift
extension AVCaptureDeviceInput {
    
    /// Returns the capture device input for the desired media type and capture session, otherwise nil.
    ///
    /// - Parameters:
    ///   - mediaType: Specified media type. (i.e. AVMediaTypeVideo, AVMediaTypeAudio, etc.)
    ///   - captureSession: Capture session for which to query
    /// - Returns: Desired capture device input for the associated media type, otherwise nil
    public class func deviceInput(withMediaType mediaType: AVMediaType, captureSession: AVCaptureSession) -> AVCaptureDeviceInput? {
        if let inputs = captureSession.inputs as? [AVCaptureDeviceInput] {
            for deviceInput in inputs {
                if deviceInput.device.hasMediaType(mediaType) {
                    return deviceInput
                }
            }
        }
        return nil
    }
    
}
```

**Comment by slash7** [comment]
``` Swift
NextLevelSession.swift:258:58: Type 'AVMediaType' (aka 'NSString') has no member 'video'
```
```Swift
extension NextLevelSession {
    
    /// Prepares a session for recording video.
    ///
    /// - Parameters:
    ///   - settings: AVFoundation video settings dictionary
    ///   - configuration: Video configuration for video output
    ///   - formatDescription: sample buffer format description
    /// - Returns: True when setup completes successfully
    public func setupVideo(withSettings settings: [String : Any]?, configuration: NextLevelVideoConfiguration, formatDescription: CMFormatDescription) -> Bool {
        self._videoInput = AVAssetWriterInput(mediaType: AVMediaType.video, outputSettings: settings, sourceFormatHint: formatDescription)
...
```

**Comment by bojanstef** [comment]
@colinmcardell this didn't work for me... trying to figure out a solution now

**Comment by colinmcardell** [comment]
Interesting.

I'm using Cocoapods to bring NextLevel into my project and I'm pointing to a specific commit like this:
`pod 'NextLevel', git: 'https://github.com/NextLevel/NextLevel.git', commit: 'ed8936a4c9f428016f16d120a0806e5c4e32970a'`

Some context around the errors that are listed above by @slash7:
- [This shows the changes in Media Types from Xcode 8.3 -> 9.0](https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/media_types?changes=latest_minor) – Previous to Swift 4 Media Types were not types and just passed around as strings (like this: https://developer.apple.com/documentation/avfoundation/avcapturedevice/2361508-default?changes=latest_minor)
- This is the commit where a variety of Swift 4 changes were put into place for NextLevel: https://github.com/NextLevel/NextLevel/commit/c3f6011fb3a6a01fe0c1d15c029d1a4596a3f958

A few questions:
1. How are you bringing NextLevel into your project?
1. What version or commit of NextLevel are you pointing to?
1. It is mentioned in the README "Need Swift 3? Use release 0.6.3." ([here](https://github.com/NextLevel/NextLevel/blob/master/README.md#quick-start)). What happens if you point to `0.6.3` (not that using `0.6.3` is the solution but more to find out if Swift 3 compatible NextLevel compiles)?

**Comment by bojanstef** [comment]
### Finally everything works

> Answers to @colinmcardell's questions:
1. In my Podfile I have `pod 'NextLevel'` 
2. This installed `0.7.2`
3. I previously used `0.6.3` but decided to upgrade today. 

> I didn't test going back to `0.6.3` but, my solution was the following:
1. Remove `pod 'NextLevel'` then run `pod install`
2. Remove all references to `NextLevel` in my MyProject.workspace
3. Convert to Swift 4 ([and fix all warnings in my target](https://stackoverflow.com/a/44380886))
4. Add `pod 'NextLevel'` then run `pod install`

> Oddly enough everything now works. In between most steps I did the "three cleans"

| Hotkey | Description |
| :--- | :--- |
| ⇧⌘K | Product > Clean |
| ⌥⇧⌘K | Product > Clean Build Folder... |
| ⌘, | Xcode > Preferences... > Locations > "then I delete the derived data folder" |

**Comment by slash7** [comment]
@colinmcardell thanks, switching to swift 4 in the build settings fixed this issue.

I've re-downloaded Xcode 8 as there is another issue, on Apple's side this time (https://forums.developer.apple.com/thread/86810) which involves using private APIs and I won't be able to submit to the AppStore using Xcode 9.

**Comment by piemonte** [comment]
hey @slash7, NextLevel 0.7.1 fixes the apple issue you mention.

📎 https://github.com/NextLevel/NextLevel/issues/99

if you want to use swift 3, you can install `0.6.3`

**Comment by piemonte** [comment]
sorry folks, would have chimed in sooner but didn't see this discussion until now.

**Comment by slash7** [comment]
@piemonte thanks, the fix is great but as you're forced to use private APIs like (```__availablePreviewPhotoPixelFormatTypes```) the app might not pass the review process.

I've moved back to swift 3 and Xcode 8 until Apple releases a fix for Xcode 9.

**Comment by piemonte** [comment]
ah, cool, sounds good. on the forum post (https://forums.developer.apple.com/thread/86810), Apple updated it and mentioned the SPI as OK but i understand trying to avoid the risk.
