### ISSUE TITLE
Can't record twice

### ISSUE THREAD

**Issue by donpark** [NextLevel/NextLevel#12]
Presenting example CameraViewController works first time only.
Second time fails at start because captureSession was not nil.
Clearing that still failed because sharedInstance had some internal variables.
Using non-singleton NextLevel instance fared better but resulted in unreleased KVO errors.
Removing KVO in deinit finally allowed CameraViewController to work multiple times.

**Comment by piemonte** [comment]
thanks @donpark will check it out.

i have some comments on the deinit because i didn't actually finish writing it, would explain the behavior you're seeing.

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevel.swift#L696

https://github.com/NextLevel/NextLevel/blob/master/Sources/NextLevel.swift#L688

**Comment by piemonte** [comment]
hey @donpark i pushed a couple changes. let me know if that addresses the issue for you, then can close this

**Comment by donpark** [comment]
Great. Unfortunately, I moved away from singleton and made bunch of changes to fit my needs so it'll be awhile before I can attempt to retry the original version. Sorry.

**Comment by piemonte** [comment]
sounds good. if you encounter it again, let m know.
