### ISSUE TITLE
Question: What is the best way to add support for effects matte?

### ISSUE THREAD

**Issue by juansanzone** [NextLevel/NextLevel#158]
This is my configuration:
```swift
        NextLevel.shared.delegate = self
        NextLevel.shared.photoDelegate = self
        NextLevel.shared.captureMode = .photo
        NextLevel.shared.photoConfiguration.codec = AVVideoCodecType.hevc.rawValue
        NextLevel.shared.devicePosition = .front
        NextLevel.shared.portraitEffectsMatteDelegate = self
        NextLevel.shared.depthDataCaptureEnabled = true
        NextLevel.shared.portraitEffectsMatteCaptureEnabled = true
        NextLevel.shared.photoConfiguration.preset = AVCaptureSession.Preset.high
        NextLevel.shared.photoConfiguration.isPortraitEffectsMatteEnabled = true
```

1) I use an iPhone X real device.
2) I call to: NextLevel.shared.capturePhoto()
3) In the following delegate, `photo.portraitEffectsMatte` and `photo.pixelBuffer` are nil. ¿Why?
`func nextLevel(_ nextLevel: NextLevel, didFinishProcessingPhoto photo: AVCapturePhoto) {`

**Comment by piemonte** [comment]
hey @juansanzone thanks for the inquiry. i haven't been using the matte feature personally but it was contributed by @giogus  recently:

📎 https://github.com/NextLevel/NextLevel/pull/144

if the PR doesn't help, maybe he has more guidance?

**Comment by juansanzone** [comment]
thanks!! I'll check!

**Comment by juansanzone** [comment]
Hi @giogus !! 
I've received the following message: `NextLevel, couldn't enable portrait effects matte delivery in the output`.

Any idea?  I use a real device (iPhone X), and the camera config are the following:

```swift
 private func initCamera() {
        NextLevel.shared.delegate = self
        NextLevel.shared.photoDelegate = self
        NextLevel.shared.captureMode = .photo
        NextLevel.shared.photoConfiguration.codec = AVVideoCodecType.hevc.rawValue
        NextLevel.shared.devicePosition = .front
        NextLevel.shared.portraitEffectsMatteDelegate = self
        NextLevel.shared.depthDataCaptureEnabled = true
        NextLevel.shared.portraitEffectsMatteCaptureEnabled = true
        NextLevel.shared.photoConfiguration.preset = AVCaptureSession.Preset.high
        NextLevel.shared.photoConfiguration.isPortraitEffectsMatteEnabled = true
    }
```

The internal NexLevel check:  `if photoOutput.isPortraitEffectsMatteDeliverySupported { ` is always FALSE, and don't know why.

**Comment by giogus** [comment]
Thanks for reaching out @juansanzone,

The Apple Documentation points out the following information:

> When capturing a photo in the iOS Camera app, you can cause the portrait effects matte to be generated by entering Portrait mode and detecting a face. You can tell whether the camera found a face by checking for four yellow brackets in the viewfinder; **photographing a detected face in Portrait mode doesn't guarantee the generation of a matte**, but it is a prerequisite.

> Even if your app opts in to matte delivery, **you're not guaranteed delivery of a matting image in the resulting AVCapturePhoto**. The neural network responsible for generating portrait effects mattes is trained to detect and segment people. **If there are no people in the image scene, the image won't benefit from a portrait effects matte, so none is delivered**.

The following piece of code checks if the following has support for the AVPortraitMatteDelivery, what device you're using to test this feature?

```
// Check that portrait effects matte delivery is supported on this particular device:
if self.photoOutput.isPortraitEffectsMatteDeliverySupported {
    self.photoOutput.isPortraitEffectsMatteDeliveryEnabled = true
}
```

The compatible devices compatible for this feature are the iPhones 7 Plus (Back Camera), 8 Plus (Back Camera), X (Both Camera), XS (Both Camera), XR (Both Camera). They also need to be running the newest iOS 12.

Thank You!
Gustavo Severo

**Comment by BoazTelem** [comment]
Hi Guys!

@juansanzone - Have you managed to fix this or you didn't use NextLevel at the end?

 @giogus and @piemonte

I don't think this feature works with NextLevel and I am not sure why.

I have further looked into it, and using the same iPad with the same subject when running AVCam App: 

https://github.com/AppTyrant/AVCamBuildingACameraApp 

The Matte is created. 

However using NextLevel, I wasn't able to make it work. Here is what I done so far to try to debug it:
1. I made sure to enable to compiler argument USE_TRUE_DEPTH (If I understand correctly this is needed).
2. I made sure to enable this feature in settings. 

Regardless, the isPortraitEffectsMatteDeliverySupported alwas return false, and it is not because it didn't detect the subject and it is not because the device is not supported. There is something else, either with the way the session is setup for it, or when switching modes from video to photo or something that is not setup right that cause the Matte feature not to be supported.

Any help will be much apricated, I am trying to figure out where the bug is.

**Comment by BoazTelem** [comment]
I think I found the issue. The problem is that if you set the _requestedDevice to the .builtInTrueDepthCamera in order to have the depth supported from the front camera if you are going through:  configureSessionDevices() more than once there is a line there that se the _requestedDevice to nil. Then next level search and choose the first device and hence not selecting a supported device. Commenting out this line:

//self._requestedDevice = nil

Will allow you to get the Depth frame you desire. 

The question is, what is the reason one want to set the requested device to nil? Did some decided that the requested Device requested in the past is no longer requested? Feels like a bug to me, will appreciate some confirmation or objection.

thank you!
