### ISSUE TITLE
Deprecated requestAuthorization 

### ISSUE THREAD

**Issue by SeanFromTheMatrix** [NextLevel/NextLevel#172]
When calling requestAuthorization: 
- ( NextLevel.shared.requestAuthorization(forMediaType: AVMediaType.audio) )
 I get a warning that it has been deprecated: 
- ( 'requestAuthorization(forMediaType:)' is deprecated on iOS: Use NextLevel.requestAuthorization(forMediaType:completionHandler) )

When I update the code to eliminate the warning, the methods inside NextLevelDelegate stop working. I am setting the delegate to self in viewDidLoad. It only works if I let the warning continue to show. This set me back a couple of hours on the project, as I was trying to stay up to date with this frame work.

**Comment by piemonte** [comment]
Hey @SeanFromTheMatrix – dang, I'm sorry to hear about your lost time. It's my fault, I should have updated the sample project with the proper use.

With the new method, you use the completionHandler instead of the callback in the delegate.

You can see here...
e51f0d792265fd8559dd9d092e79d76a14cb6595
