### ISSUE TITLE
previewView not updated with camera view on second presentation of CameraViewController

### ISSUE THREAD

**Issue by thexande** [NextLevel/NextLevel#19]
First off, amazing Lib.

I am using NextLevel in one of my apps and I need to present the CameraViewController() multiple times modally to allow for video capture. Everything is working well until I present the CameraViewController for a second time, and the previewView does not update to the NextLevel.sharedInstance.previewLayer. The previewView will update if the camera is flipped and then flipped back. 

I have created a video detailing the bug. 
https://www.youtube.com/watch?v=TztPcTT5TKk&feature=youtu.be

The culprit is on line ~90 of CameraViewController 

```Swift
        
        // preview
        self.previewView = self.cameraView
        if let previewView = self.previewView {
            previewView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
            previewView.backgroundColor = UIColor.blue
            NextLevel.sharedInstance.previewLayer.frame = previewView.bounds
            previewView.layer.addSublayer(NextLevel.sharedInstance.previewLayer)
            self.view.addSubview(previewView)
        }
```

Thanks again for sharing this Lib with all of us!!!!

**Comment by protosphere** [comment]
I'm experiencing the same issue: If `NextLevel.sharedInstance.start()` is called after calling `NextLevel.sharedInstance.stop()`, the preview will be blank and you will be unable to capture photos (or videos).

After investigating this, I found that the `AVCaptureSession` does not get any inputs added to it when `NextLevel` is stopped and later started again. The problem appears to be in [`configureSessionDevices`](https://github.com/NextLevel/NextLevel/blob/aae16efb4fe1041735f9afc72f9566ab5ad3f439/Sources/NextLevel.swift#L884-L898):

```swift
if let device = captureDevice {
    if device != self._currentDevice {
        self.configureDevice(captureDevice: device, mediaType: AVMediaTypeVideo)

        let changingPosition = device.position != self._currentDevice?.position
        if changingPosition == true {
            self.executeClosureAsyncOnMainQueueIfNecessary {
                self.deviceDelegate?.nextLevelDevicePositionWillChange(self)
            }
        }

        self.willChangeValue(forKey: "currentDevice")
        self._currentDevice = device
        self.didChangeValue(forKey: "currentDevice")
        self._requestedDevice = nil
```

In the first call to `configureSessionDevices`, `self._currentDevice` will be `nil`, so `self.configureDevice(captureDevice:mediaType:)` will be called, adding the appropriate inputs to `self._captureSession`.

However, after stopping the session and starting it again, `self._currentDevice` will still contain the most recently used device. Since `devicePosition` hasn't been switched in the meantime, this means that `device` will be equal to `self._currentDevice`, causing the call to `self.configureDevice(captureDevice:mediaType:)` to be skipped. Thus, no inputs are added to the newly created session.

This would also explain the behaviour described in the first comment; changing `devicePosition`  will satisfy the `device != self._currentDevice` condition and allow the input to be added to the session.

I'm happy to submit a PR for this, but I have a couple of questions first:

* Should `self._currentDevice` be set to `nil` after the session has been stopped via `NextLevel.sharedInstance.stop()`?
* Or, should the [block of code](https://github.com/NextLevel/NextLevel/blob/aae16efb4fe1041735f9afc72f9566ab5ad3f439/Sources/NextLevel.swift#L999-L1008) responsible for adding the inputs to the session be extracted into another function and called regardless of whether the device has changed?

Thanks!

**Comment by piemonte** [comment]
Hey @protosphere thanks for investigating! To answer your questions:

`Should self._currentDevice be set to nil after the session has been stopped via NextLevel.sharedInstance.stop()?`
Yes.

`Or, should the block of code responsible for adding the inputs to the session be extracted into another function and called regardless of whether the device has changed?`
To be honest, you're right, there could be an addInputs to better reflect the removeInputs func – instead of just addInput, but it isn't completely necessary. You could even refactor addInput to be addInputs and have it do more device lookups.

**Comment by piemonte** [comment]
PR's are welcome

**Comment by piemonte** [comment]
@thexande if you see any issues with master, please let us know
