### ISSUE TITLE
What's the status of the sample app?

### ISSUE THREAD

**Issue by rogerluan** [NextLevel/NextLevel#253]
Hey, it's me again :bowtie: 

I've been looking for a camera SDK to work with, and this seems to be the only maintained SDK out there (the others I found were last updated anywhere between 2016, 2018, 2020...).

However, when I started playing with the sample app, I got very confused, as I couldn't figure out how to take a single picture, nor how to zoom, even though the documentation claims both of these features should be possible. Also, the checkmark ☑️ near the shutter button has a very cryptic purpose (at least to me), UX-wise - although I think I got that it's meant to preview a previously recorded video.

This raised a few questions:
- Am I doing something wrong? I'm not sure if this was just me not knowing how to use the sample app (e.g. user error, or UX issue).
- Does the SDK really support those 2 features I mentioned (zooming gesture and single-picture capture)? Perhaps they just weren't configured on the sample app.

Looking forward to hear more from the maintainers. I appreciate the time you put into developing and maintaining this project 💪 Seems to be one of the few camera SDKs standing 😄 

Cheers!

**Comment by piemonte** [comment]
hey @rogerluan,

first off, thanks for the project interest! forgive me, i have limited time, but i do my best to provide open software such that people can learn, build, and contribute over time without me having to get too involved. 😄

so there's two sample apps currently. the one that's part of the main repo here and the other that shows how to integrate with ARKit found [here](https://github.com/NextLevel/examples).

the AVFoundation photo capture API has changed dramatically over the past couple years and since this library has been primarily used for video, i haven't kept up with the photo capture changes. major changes. i've started to update them as much as possible but it's a big time investment for something i'm not using professional in any way. the library's example files could definitely be updated too. even my own personal programming style has changed since i first put these together.

so it's not you! it's me. 😊 i am integrating this project again into a big new thing but it's also primarily being used for video.

you can do photo frame capture from video, which is what i recommend and most video-first apps do. there are some issues on the topic and you can find it in the docs. yes, zooming is supported also but i don't know if there's an example of the gesture itself –would have to see if i have it and share sometime. hope this helps.

**Comment by rogerluan** [comment]
Thank you @piemonte ! Yes, that certainly helps!

If I decide to use this lib on a project, I'll be actively contributing to the photo experience and new APIs 💪 But for now, I haven't made up my mind yet.

Awesome work you did here! Thanks for your strong dedication towards this lib! 🚀
