### ISSUE TITLE
Remove clip time error

### ISSUE THREAD

**Issue by adriantabirta** [NextLevel/NextLevel#41]
When I try to delete clip and than record another  one session duration is NAN. I found a solution. The proble is weh you substract session duration. 

>     public func remove(clipAt idx: Int, removeFile: Bool) {
        self.executeClosureSyncOnSessionQueueIfNecessary {
            if self._clips.indices.contains(idx) {
                let clip = self._clips.remove(at: idx)
                
              //  Use  CMTimeSubtract to substract CMTime
              //  and substration should be before clip.remove()

                self._duration = CMTimeSubtract(self._duration, clip.duration)
                
                if removeFile {
                    clip.removeFile()
                }
  
            }
        }
    }

**Comment by piemonte** [comment]
hey @adriantabirta, i appreciate the feedback! it looks like a couple things are happening.

we should definitely remove the file after the duration has been re-calculated, like you have there.

the NaN is probably happening because the clip's duration is TimeInvalid vs Zero, which is interesting in terms of the handling of CMTimeSubtract vs a swift operator. I'd have to test this to see what's happening.

**Comment by piemonte** [comment]
298d1513993ca8af5d34dd7d08711cb3faa3a87d

**Comment by piemonte** [comment]
@adriantabirta this should be fixed now, if you still see issues, let me know. thanks for the help.
