### ISSUE TITLE
it caused to freeze during switch photo to video

### ISSUE THREAD

**Issue by asmcn** [NextLevel/NextLevel#74]
In version 0.3.9 caused to freeze during switch photo to video mode. Update device orientation function may be suspect of this issue.

**Comment by dgon-jd** [comment]
Up. Freezes on mode change.

**Comment by piemonte** [comment]
thanks, please install 0.3.12 and let me know if you see the same issue.

**Comment by tonymuu** [comment]
Hi, I'm still experiencing a roughly two-second freeze when switching between photo and video modes. Is that normal? Is there anyway to avoid that?

**Comment by piemonte** [comment]
hey @tonymuu – changing modes will have some delay but there could also be a bug making it even slightly longer too. in my projects, i use the `capturePhotoFromVideo` func instead of the full photo mode to avoid those delays. just depends on your use cases and capture quality preferences. 

i'm tracking this mode change issue with :
📎 https://github.com/NextLevel/NextLevel/issues/16

**Comment by tonymuu** [comment]
hi @piemonte thanks for the quick reply! The `capturePhotoFromVideo` works perfectly! Thank you
