### ISSUE TITLE
Camera Freezes when In call bar is showing

### ISSUE THREAD

**Issue by Wouter125** [NextLevel/NextLevel#8]
I recently build my own camera application and that was having the same problem as this API. Whenever someone calls me and I open up my application, the camera freezes on 1 frame and that freezed frame gets really dark. Do you have any idea why this happens / how to fix it?

**Comment by piemonte** [comment]
hey @Wouter125, thanks for the note. i haven't experimented with this particular case since it's more niche.

it sounds like the preview layer goes into an inactive/background state when the bar comes up. you can use your own rendering context for video frames instead of using a the videoPreviewLayer itself, which may get around this for you. that's actually what i'm doing in my apps. (you just render the camera output into a GLKView/SCNView or MTLView) PBJVision does this with the "onion skinning" feature with a GLKViewController, if you need an example.

📎 https://github.com/piemonte/PBJVision/blob/master/Project/Vision/PBJViewController.m#L198-L206

I have some code that does with NextLevel in for both a metal and OpenGL context but haven't had the chance to OS it.
